# $$\    $$\                    $$\ $$\ $$\            $$$$$$\  $$\       
# $$ |   $$ |                   \__|$$ |$$ |          $$  __$$\ $$ |      
# $$ |   $$ |$$$$$$\  $$$$$$$\  $$\ $$ |$$ | $$$$$$\  $$ /  \__|$$$$$$$\  
# \$$\  $$  |\____$$\ $$  __$$\ $$ |$$ |$$ | \____$$\ \$$$$$$\  $$  __$$\ 
#  \$$\$$  / $$$$$$$ |$$ |  $$ |$$ |$$ |$$ | $$$$$$$ | \____$$\ $$ |  $$ |
#   \$$$  / $$  __$$ |$$ |  $$ |$$ |$$ |$$ |$$  __$$ |$$\   $$ |$$ |  $$ |
#    \$  /  \$$$$$$$ |$$ |  $$ |$$ |$$ |$$ |\$$$$$$$ |\$$$$$$  |$$ |  $$ |
#     \_/    \_______|\__|  \__|\__|\__|\__| \_______| \______/ \__|  \__|
#Discord de VanillaShop : https://discord.gg/BD6HpjQ9JF                                                                        
#Config                                                    
motd: "By VanillaShop"
